app:
  datasource:
    name: faster-cms
    host: 139.199.23.31
    port: 3306
    username: root
    password: 18764050615
  upload:
    local:
      file-dir: /data/upload/faster-cms
      url-prefix: http://127.0.0.1:8080